<?xml version="1.0" encoding="utf-8"?><Database Name="CSBaseECommerce" Class="CSCommerceDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CSDBServer101;Initial Catalog=CSBaseECommerce;Integrated Security=True" SettingsObjectName="CSData.Properties.Settings" SettingsPropertyName="CSBaseECommerceConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Visible" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Orderno" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Address" Member="Addresses">
    <Type Name="Address">
      <Column Name="AddressId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FaxNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StateProvince" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ZipPostalCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CountryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustomField" Member="CustomFields">
    <Type Name="CustomField">
      <Column Name="FieldId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FieldName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FieldType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VersionCategory" Member="VersionCategories">
    <Type Name="VersionCategory">
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Visible" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Version" Member="Versions">
    <Type Name="Version">
      <Column Name="VersionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ShortName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Visible" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ShippingOrderValue" Member="ShippingOrderValues">
    <Type Name="ShippingOrderValue">
      <Column Name="ShippingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderTotal" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Cost" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="TypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IncludeRushShipping" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PrefId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SkuShipping" Member="SkuShippings">
    <Type Name="SkuShipping">
      <Column Name="SkuShippingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SkuId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cost" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="IncludeRushShipping" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PrefId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ShippingPref" Member="ShippingPrefs">
    <Type Name="ShippingPref">
      <Column Name="PrefId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OptionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="flatShipping" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="InCludeRushShipping" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RushShippingCost" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="RushOptionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsCustomized" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="ShippingPref_ShippingCharge" Member="ShippingCharges" ThisKey="PrefId" OtherKey="PrefId" Type="ShippingCharge" />
    </Type>
  </Table>
  <Table Name="dbo.ShippingRegion" Member="ShippingRegions">
    <Type Name="ShippingRegion">
      <Column Name="RegionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CountryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StateId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrefId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Coupon" Member="Coupons">
    <Type Name="Coupon">
      <Column Name="CouponId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="IsPercentage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SitePref" Member="SitePrefs">
    <Type Name="SitePref">
      <Column Name="PrefId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="PathOrderDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="OrderTotalShipping" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ArchiveData" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GeoTargetService" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PaymentGatewayService" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FulfillmentHouseService" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SiteHeader" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="LogoPath" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="OrderProcessType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SiteName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="SiteUrl" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ShippingCharges" Member="ShippingCharges">
    <Type Name="ShippingCharge">
      <Column Name="ShippingChargeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PrefId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Cost" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="FriendlyLabel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="ShippingPref_ShippingCharge" Member="ShippingPref" ThisKey="PrefId" OtherKey="PrefId" Type="ShippingPref" IsForeignKey="true" />
    </Type>
  </Table>
</Database>